### ISSUE TITLE
Addition of day 17 and day 18  ( doing open source contributions through go Lang) to tools like kubernities, Prometheus 

### ISSUE THREAD

**Issue by deepak4566** [sd031/go-for-devops#1]
Addition of day 17 and day 18  ( doing open source contributions through go Lang) to tools like kubernities, Prometheus etc
-> understanding devops tools like k8's,Prometheus,argo cd code bases which are natively written in go Lang
-> understanding how to contribute to these issues in these devops tools
-> doing live open source contributions in go lang for k8's ,argocd , Prometheus etc 

@sd031 If this is ok for u to add in course ,that is too good for the community 
Thanks for the course once again ☺️

**Comment by rajgaurav79** [comment]
pls assign this issue to me sir
